name: nt96650_app
description: A Flutter app to control NT96650
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  xml: ^6.2.2
  provider: ^6.1.1
  video_player: ^2.8.1
  media_kit: ^1.1.9
  media_kit_video: ^1.2.7
  media_kit_libs_video: ^1.0.5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  wifi_scan: ^0.4.1+2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
